# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handshake.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='handshake.proto',
  package='handshake_proto',
  syntax='proto3',
  serialized_options=b'\n#java_fmu.main.proto.handshake_protoB\016HandshakeProtoH\001P\000\252\002\016HandshakeProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fhandshake.proto\x12\x0fhandshake_proto\"1\n\rHandshakeInfo\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"\x06\n\x04Void2Y\n\nHandshaker\x12K\n\x10PerformHandshake\x12\x1e.handshake_proto.HandshakeInfo\x1a\x15.handshake_proto.Void\"\x00\x42J\n#java_fmu.main.proto.handshake_protoB\x0eHandshakeProtoH\x01P\x00\xaa\x02\x0eHandshakeProtob\x06proto3'
)




_HANDSHAKEINFO = _descriptor.Descriptor(
  name='HandshakeInfo',
  full_name='handshake_proto.HandshakeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_address', full_name='handshake_proto.HandshakeInfo.ip_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='handshake_proto.HandshakeInfo.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=85,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='handshake_proto.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['HandshakeInfo'] = _HANDSHAKEINFO
DESCRIPTOR.message_types_by_name['Void'] = _VOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HandshakeInfo = _reflection.GeneratedProtocolMessageType('HandshakeInfo', (_message.Message,), {
  'DESCRIPTOR' : _HANDSHAKEINFO,
  '__module__' : 'handshake_pb2'
  # @@protoc_insertion_point(class_scope:handshake_proto.HandshakeInfo)
  })
_sym_db.RegisterMessage(HandshakeInfo)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'handshake_pb2'
  # @@protoc_insertion_point(class_scope:handshake_proto.Void)
  })
_sym_db.RegisterMessage(Void)


DESCRIPTOR._options = None

_HANDSHAKER = _descriptor.ServiceDescriptor(
  name='Handshaker',
  full_name='handshake_proto.Handshaker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=95,
  serialized_end=184,
  methods=[
  _descriptor.MethodDescriptor(
    name='PerformHandshake',
    full_name='handshake_proto.Handshaker.PerformHandshake',
    index=0,
    containing_service=None,
    input_type=_HANDSHAKEINFO,
    output_type=_VOID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HANDSHAKER)

DESCRIPTOR.services_by_name['Handshaker'] = _HANDSHAKER

# @@protoc_insertion_point(module_scope)
