# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import handshake_pb2 as handshake__pb2


class HandshakerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PerformHandshake = channel.unary_unary(
                '/handshake_proto.Handshaker/PerformHandshake',
                request_serializer=handshake__pb2.HandshakeInfo.SerializeToString,
                response_deserializer=handshake__pb2.Void.FromString,
                )


class HandshakerServicer(object):
    """The greeting service definition.
    """

    def PerformHandshake(self, request, context):
        """Send a message for performing a handshake
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandshakerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PerformHandshake': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformHandshake,
                    request_deserializer=handshake__pb2.HandshakeInfo.FromString,
                    response_serializer=handshake__pb2.Void.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'handshake_proto.Handshaker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Handshaker(object):
    """The greeting service definition.
    """

    @staticmethod
    def PerformHandshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/handshake_proto.Handshaker/PerformHandshake',
            handshake__pb2.HandshakeInfo.SerializeToString,
            handshake__pb2.Void.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
