# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import unifmu_fmi2_pb2 as unifmu__fmi2__pb2


class SendCommandStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fmi2DoStep = channel.unary_unary(
                '/unifmu_fmi2_proto.SendCommand/Fmi2DoStep',
                request_serializer=unifmu__fmi2__pb2.DoStep.SerializeToString,
                response_deserializer=unifmu__fmi2__pb2.StatusReturn.FromString,
                )
        self.Fmi2SetReal = channel.unary_unary(
                '/unifmu_fmi2_proto.SendCommand/Fmi2SetReal',
                request_serializer=unifmu__fmi2__pb2.SetReal.SerializeToString,
                response_deserializer=unifmu__fmi2__pb2.StatusReturn.FromString,
                )
        self.Fmi2GetReal = channel.unary_unary(
                '/unifmu_fmi2_proto.SendCommand/Fmi2GetReal',
                request_serializer=unifmu__fmi2__pb2.GetXXX.SerializeToString,
                response_deserializer=unifmu__fmi2__pb2.GetRealReturn.FromString,
                )


class SendCommandServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Fmi2DoStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fmi2SetReal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fmi2GetReal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SendCommandServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fmi2DoStep': grpc.unary_unary_rpc_method_handler(
                    servicer.Fmi2DoStep,
                    request_deserializer=unifmu__fmi2__pb2.DoStep.FromString,
                    response_serializer=unifmu__fmi2__pb2.StatusReturn.SerializeToString,
            ),
            'Fmi2SetReal': grpc.unary_unary_rpc_method_handler(
                    servicer.Fmi2SetReal,
                    request_deserializer=unifmu__fmi2__pb2.SetReal.FromString,
                    response_serializer=unifmu__fmi2__pb2.StatusReturn.SerializeToString,
            ),
            'Fmi2GetReal': grpc.unary_unary_rpc_method_handler(
                    servicer.Fmi2GetReal,
                    request_deserializer=unifmu__fmi2__pb2.GetXXX.FromString,
                    response_serializer=unifmu__fmi2__pb2.GetRealReturn.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unifmu_fmi2_proto.SendCommand', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SendCommand(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Fmi2DoStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unifmu_fmi2_proto.SendCommand/Fmi2DoStep',
            unifmu__fmi2__pb2.DoStep.SerializeToString,
            unifmu__fmi2__pb2.StatusReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Fmi2SetReal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unifmu_fmi2_proto.SendCommand/Fmi2SetReal',
            unifmu__fmi2__pb2.SetReal.SerializeToString,
            unifmu__fmi2__pb2.StatusReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Fmi2GetReal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unifmu_fmi2_proto.SendCommand/Fmi2GetReal',
            unifmu__fmi2__pb2.GetXXX.SerializeToString,
            unifmu__fmi2__pb2.GetRealReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
